---
title: "SmartQuestion2"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
knitr::opts_chunk$set(warning = F, results = "markup", message = F)
#knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r}
loadPkg("ggplot2")
# Reading the dataset
salesdata = read.csv("Sales_Transaction.csv")

ggplot(salesdata, aes(y=Quantity)) + 
  geom_boxplot() + 
  geom_boxplot( colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) +
  labs(title="Quantity boxplot using `ggplot`",x="", y = "Quantity")

ggplot(salesdata, aes(y=Price)) + 
  geom_boxplot() + 
  geom_boxplot( colour="blue", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) +
  labs(title="Price boxplot using `ggplot`",x="", y = "Quantity")


```

```{r}
library("ggplot2")
quantityoutlier = outlierKD2(salesdata, Quantity, rm=TRUE, boxplt=TRUE, histogram=TRUE, qqplt=TRUE) 
```
```{r}
ggplot(data=salesdata)+
  geom_point(mapping = aes(x=Quantity, y=Price))+
  ggtitle("Scatter plot of Price vs Quantity)")+
  coord_cartesian(xlim = c(0, max(salesdata$Quantity) * 1.1),  # Adjust the multiplier to control the range
                  ylim = c(0, max(salesdata$Price) * 1.1))
  
```