

---
title: "Q3"
author: "Ganesh Kumar Boini"
date: "March 16 2024"
# date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
knitr::opts_chunk$set(warning = F, results = "markup", message = F)
#knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

## Loading the dataset

```{r}
# Reading the dataset

salesdata = read.csv("Sales_Transaction.csv")

# Structure of the dataset

str(salesdata)

```

```{r}
library("ggplot2")


threshold <- quantile(salesdata$Price, 0.9)
high_value_customers <- unique(salesdata$CustomerNo[salesdata$Price > threshold])
high_value_customers

high_value_transactions <- subset(salesdata, CustomerNo %in% high_value_customers)
average_transaction_amount <- mean(high_value_transactions$Price)

high_value_transactions

average_transaction_amount
```